#!/usr/bin/env python
"""Record the exact environment a result was produced in.

The brief requires a pinned environment and a headline number that reproduces
from a clean checkout. `requirements.txt` states the ranges we support;
`requirements.lock.txt`, written by this script, states what was actually
installed on the machine that produced the numbers in the paper.

Run it once inside the booked window, immediately after the headline pair, and
commit the result alongside the metrics.

    python scripts/freeze_env.py
"""

from __future__ import annotations

import json
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def pip_freeze() -> str:
    result = subprocess.run(
        [sys.executable, "-m", "pip", "freeze"], capture_output=True, text=True, check=False
    )
    return result.stdout


def hardware() -> dict[str, object]:
    info: dict[str, object] = {
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "processor": platform.processor(),
        "captured_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    try:
        import torch
    except ImportError:
        info["torch"] = "not installed"
        return info

    info["torch"] = torch.__version__
    info["cuda_available"] = torch.cuda.is_available()
    if torch.cuda.is_available():
        info["cuda"] = torch.version.cuda
        info["gpus"] = [
            {
                "name": torch.cuda.get_device_properties(i).name,
                "total_memory_gb": round(
                    torch.cuda.get_device_properties(i).total_memory / 1024**3, 2
                ),
            }
            for i in range(torch.cuda.device_count())
        ]
    return info


def main() -> int:
    lock = REPO_ROOT / "requirements.lock.txt"
    frozen = pip_freeze()
    header = (
        "# Exact versions present on the machine that produced the reported results.\n"
        "# Generated by scripts/freeze_env.py -- do not edit by hand.\n"
    )
    lock.write_text(header + frozen, encoding="utf-8")

    env_path = REPO_ROOT / "results" / "environment.json"
    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text(json.dumps(hardware(), indent=2), encoding="utf-8")

    print(f"wrote {lock.relative_to(REPO_ROOT)} ({len(frozen.splitlines())} packages)")
    print(f"wrote {env_path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
